runtime: python
vm: true
entrypoint: gunicorn -b :$PORT run:app

runtime_config:
  python_version: 3

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: run.app

libraries:
  - name: ssl
    version: latest